### ISSUE TITLE
charter.md Clarify the relationship with the Metrics sub-project in the data science SIG

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#66]
Metrics Strategic vs Metrics
[Metrics](https://github.com/open-services-group/community/tree/main/sig-data-science#metrics-1)

**Comment by codificat** [comment]
As per recent SIG Community Experience meetings, the decision was made to close the sub-projects and handle everything at the SIG level. See #178 for more details.

From the SIG Data Science side, SP metrics owns the [metrics](https://github.com/open-services-group/metrics) repository and will continue to maintain it as appropriate - also from within the context of the Data Science SIG.

Based on that, I believe that this issue is no longer relevant, so:
/close
